services:
  redis:
    image: redis
    command: [ "redis-server", "--requirepass", "your-redis-password" ]
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"

  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"

  mailpit:
    image: axllent/mailpit
    ports:
      - "127.0.0.1:8025:8025" # Mailpit web UI
      - "127.0.0.1:1025:1025" # SMTP port

  web:
    build: .
    env_file:
      - ./docker.env
    depends_on:
      - postgres
      - redis
      - mailpit
    ports:
      - "3000:3000"
    volumes:
      - outline-data:/var/lib/outline/data

volumes:
  outline-data:
